-- Add remaining 17 Memphis area venues to preferred_venues table
-- Run this directly in Supabase SQL Editor after the first 10 venues

INSERT INTO preferred_venues (
  venue_name,
  venue_type,
  address,
  city,
  state,
  zip_code,
  website,
  description,
  capacity_min,
  capacity_max,
  amenities,
  is_featured,
  is_active
) VALUES 
(
  'Central Station Hotel',
  'hotel',
  '545 S Main St',
  'Memphis',
  'TN',
  '38103',
  'https://centralstationmemphis.com',
  'Boutique hotel inside a 1914 train station blending Memphis'' musical soul with modern design. Features exposed brick and soaring ceilings for an industrial-chic vibe.',
  60,
  200,
  ARRAY['historic architecture', 'accommodations', 'parking', 'industrial design'],
  true,
  true
),
(
  'Avon Acres',
  'banquet_hall',
  '8025 Walnut Grove Rd',
  'Memphis',
  'TN',
  '38138',
  'https://www.uniquevenues.com/venue/avon-acres-memphis',
  'Elegant banquet hall-style venue covering 5,800 sq ft, immersing guests in a modern, sophisticated atmosphere with rustic glamour. Offers indoor–outdoor flexibility for up to 350 guests.',
  75,
  350,
  ARRAY['modern design', 'outdoor space', 'large capacity', 'parking'],
  false,
  true
),
(
  'The Balinese Ballroom',
  'banquet_hall',
  '1834 Madison Ave',
  'Memphis',
  'TN',
  '38104',
  'http://www.balineseballroom.com',
  'Historic downtown venue with three flexible event spaces in a vintage setting. Exposed brick, hardwood floors, and a charming ambiance provide an authentic backdrop.',
  50,
  200,
  ARRAY['historic architecture', 'multiple spaces', 'urban location', 'parking'],
  false,
  true
),
(
  'The Cadre Building',
  'historic',
  '395 S Main St',
  'Memphis',
  'TN',
  '38103',
  'http://www.cadrememphis.com',
  '1928 Art Deco ballroom adorned with towering columns and crystal chandeliers. A glamorous historic venue known for its grand architectural elegance in downtown Memphis.',
  100,
  300,
  ARRAY['historic architecture', 'ballroom', 'elegant decor', 'urban location'],
  true,
  true
),
(
  'The Columns at One Commerce Square',
  'historic',
  '1 Commerce Square',
  'Memphis',
  'TN',
  '38103',
  'http://www.thecolumnsmemphis.com',
  'Grand 1929 bank lobby turned gala venue, defined by towering Ionic columns and vast marble interiors. Delivers a monumental historic setting ideal for large formal events.',
  150,
  400,
  ARRAY['historic architecture', 'elegant decor', 'large capacity', 'urban location'],
  true,
  true
),
(
  'Old Dominick Distillery',
  'restaurant',
  '305 S Front St',
  'Memphis',
  'TN',
  '38103',
  'https://olddominick.com',
  'Working distillery offering a one-of-a-kind industrial venue with whiskey barrels and river views.',
  40,
  150,
  ARRAY['unique venue', 'river views', 'industrial design', 'urban location'],
  false,
  true
),
(
  'Memphis Brooks Museum of Art',
  'historic',
  '1934 Poplar Ave',
  'Memphis',
  'TN',
  '38104',
  'https://www.brooksmuseum.org',
  'Historic art museum providing a spectacular backdrop surrounded by world-class art in a tranquil park setting.',
  50,
  200,
  ARRAY['art collection', 'historic architecture', 'scenic views', 'parking'],
  false,
  true
),
(
  'Heartwood Hall',
  'outdoor',
  '9825 Highway 57',
  'Rossville',
  'TN',
  '38066',
  'https://heartwoodhall.wheree.com',
  'Historic 1840 estate on 25 wooded acres blending rustic charm with modern elegance. Enchanting gardens, a lakeside ceremony site, and a refurbished barn create a memorable country celebration.',
  60,
  250,
  ARRAY['historic architecture', 'outdoor space', 'rustic barn', 'lakeside', 'garden'],
  true,
  true
),
(
  'Cedar Hall',
  'historic',
  '6700 Raleigh LaGrange Rd',
  'Bartlett',
  'TN',
  '38135',
  'https://www.evergroveestates.com/cedar-hall',
  'Antebellum manor with formal gardens and an English equestrian-style stable for receptions. Offers elegant indoor and outdoor settings on a picturesque estate.',
  50,
  180,
  ARRAY['historic architecture', 'garden', 'outdoor space', 'elegant decor'],
  false,
  true
),
(
  'Orion Hill',
  'outdoor',
  '11975 Macon Rd',
  'Arlington',
  'TN',
  '38002',
  'https://www.orionhillevents.com',
  '1830s estate on 20 acres just outside Memphis—a scenic countryside oasis with multiple indoor and outdoor spaces for versatile celebrations.',
  40,
  200,
  ARRAY['historic architecture', 'outdoor space', 'scenic views', 'multiple spaces'],
  false,
  true
),
(
  'The Robinshaw',
  'banquet_hall',
  '11600 Macon Rd',
  'Rossville',
  'TN',
  '38066',
  'https://memphisweddingsvenue.com',
  'New 12,000 sq ft event center on a 150-acre estate near Rossville. A bright venue with lakeside and oak grove ceremony sites, hosting up to 350 guests in country style.',
  100,
  350,
  ARRAY['large capacity', 'lakeside', 'outdoor space', 'modern design'],
  false,
  true
),
(
  'Pin Oak Farms',
  'outdoor',
  '1445 Feathers Chapel Rd',
  'Somerville',
  'TN',
  '38068',
  'https://www.pinoakfarms.org',
  'Rustic-elegant barn venue on a private 10-acre property surrounded by mature trees. A charming pond and wooded scenery provide a peaceful countryside setting for weddings.',
  40,
  150,
  ARRAY['rustic barn', 'outdoor space', 'scenic views', 'pond'],
  false,
  true
),
(
  'Mallard''s Croft',
  'outdoor',
  '4495 Mallards Croft Lane',
  'Byhalia',
  'MS',
  '38611',
  'https://mallardscroft.com',
  'Expansive farm venue featuring a glass-walled forest chapel for enchanting ceremonies and a modern barn-style hall for receptions. A luxurious yet rustic destination just outside Memphis.',
  60,
  300,
  ARRAY['chapel', 'rustic barn', 'outdoor space', 'modern design'],
  true,
  true
),
(
  'The Gin at Nesbit',
  'historic',
  '4325 Goodman Rd',
  'Nesbit',
  'MS',
  '38651',
  'https://www.theginatnesbit.com',
  'Restored historic cotton gin featuring 13,000 sq ft of stylish industrial event space. Blends vintage mill charm with modern amenities for a unique wedding backdrop in Mississippi.',
  100,
  400,
  ARRAY['historic architecture', 'industrial design', 'large capacity', 'unique venue'],
  true,
  true
),
(
  'Bonne Terre Inn & Chapel',
  'hotel',
  '4715 Church Rd W',
  'Nesbit',
  'MS',
  '38651',
  'https://bonneterre.co',
  '23-acre estate with a white chapel, on-site inn, restaurant, and pool. A relaxed scenic venue 20 minutes from Memphis, offering all-inclusive convenience for weddings.',
  50,
  200,
  ARRAY['chapel', 'accommodations', 'catering available', 'pool', 'outdoor space'],
  false,
  true
),
(
  'Pike & West',
  'historic',
  '7945 Poplar Pike',
  'Germantown',
  'TN',
  '38138',
  'https://pikeandwest.com',
  'Modern art gallery venue opened in 2023, offering a fresh, creative space with a multi-story patio for intimate weddings in Germantown.',
  30,
  100,
  ARRAY['art collection', 'modern design', 'outdoor space', 'intimate venue'],
  false,
  true
),
(
  'Snowden House',
  'historic',
  '1000 Snowden Circle',
  'Horseshoe Lake',
  'AR',
  '72348',
  'https://www.facebook.com/snowdenhouse',
  'Historic lakefront mansion at Horseshoe Lake surrounded by magnolias and cypress trees. A serene Southern backdrop for weddings on the lawn up to 400 guests, 32 miles from Memphis.',
  80,
  400,
  ARRAY['historic architecture', 'lakefront', 'outdoor space', 'scenic views', 'large capacity'],
  true,
  true
);

-- Verify the additional venues were inserted
SELECT 
  venue_name, 
  city, 
  state, 
  venue_type, 
  capacity_max,
  is_featured
FROM preferred_venues 
WHERE venue_name IN (
  'Central Station Hotel',
  'Avon Acres',
  'The Balinese Ballroom',
  'The Cadre Building',
  'The Columns at One Commerce Square',
  'Old Dominick Distillery',
  'Memphis Brooks Museum of Art',
  'Heartwood Hall',
  'Cedar Hall',
  'Orion Hill',
  'The Robinshaw',
  'Pin Oak Farms',
  'Mallard''s Croft',
  'The Gin at Nesbit',
  'Bonne Terre Inn & Chapel',
  'Pike & West',
  'Snowden House'
)
ORDER BY city, venue_name;

-- Final count check
SELECT 
  COUNT(*) as total_venues,
  COUNT(CASE WHEN is_featured = true THEN 1 END) as featured_venues,
  COUNT(CASE WHEN state = 'TN' THEN 1 END) as tennessee_venues,
  COUNT(CASE WHEN state = 'MS' THEN 1 END) as mississippi_venues,
  COUNT(CASE WHEN state = 'AR' THEN 1 END) as arkansas_venues
FROM preferred_venues;