-- Insert Memphis area wedding venues into preferred_venues table
-- Run this directly in Supabase SQL Editor

INSERT INTO preferred_venues (
  venue_name,
  venue_type,
  address,
  city,
  state,
  zip_code,
  website,
  description,
  capacity_min,
  capacity_max,
  amenities,
  is_featured,
  is_active
) VALUES 
(
  'The Peabody Hotel',
  'hotel',
  '149 Union Ave',
  'Memphis',
  'TN',
  '38103',
  'https://www.peabodymemphis.com',
  'Iconic luxury hotel dubbed "The South''s Grand Hotel," offering historic charm, opulent ballrooms, and its famous resident ducks.',
  50,
  400,
  ARRAY['parking', 'elegant decor', 'accommodations', 'catering available'],
  true,
  true
),
(
  'Memphis Botanic Garden',
  'outdoor',
  '750 Cherry Rd',
  'Memphis',
  'TN',
  '38117',
  'https://membg.org',
  '96-acre garden oasis with indoor and outdoor venues amid specialty gardens and arboretum vistas. A haven for nature-loving couples seeking romantic natural backdrops.',
  50,
  300,
  ARRAY['outdoor space', 'garden', 'scenic views', 'parking'],
  true,
  true
),
(
  'Dixon Gallery & Gardens',
  'historic',
  '4339 Park Ave',
  'Memphis',
  'TN',
  '38117',
  'https://www.dixon.org',
  'Art museum and garden venue offering an artful ambiance with blooming gardens. Ideal for intimate weddings that blend artistic elegance with natural beauty.',
  30,
  150,
  ARRAY['art collection', 'garden', 'historic architecture', 'parking'],
  false,
  true
),
(
  'Graceland''s Chapel in the Woods',
  'outdoor',
  '3734 Elvis Presley Blvd',
  'Memphis',
  'TN',
  '38116',
  'https://www.graceland.com/chapel-in-the-woods',
  'Quaint white chapel in a serene forest on Elvis Presley''s Graceland estate. An intimate, charming site for couples seeking a private, music-inspired ceremony in the woods.',
  20,
  80,
  ARRAY['chapel', 'outdoor space', 'historic significance', 'parking'],
  true,
  true
),
(
  'The Guest House at Graceland',
  'hotel',
  '3600 Elvis Presley Blvd',
  'Memphis',
  'TN',
  '38116',
  'https://guesthousegraceland.com',
  'Four-Diamond resort hotel adjacent to Graceland, featuring elegant ballrooms and a private theater. Offers full-service wedding packages in an Elvis-inspired luxury setting.',
  100,
  350,
  ARRAY['ballroom', 'accommodations', 'catering available', 'elegant decor', 'parking'],
  true,
  true
),
(
  'Woodruff-Fontaine House',
  'historic',
  '680 Adams Ave',
  'Memphis',
  'TN',
  '38105',
  'http://www.woodruff-fontaine.org',
  'Victorian-era mansion providing a timeless 19th-century backdrop with ornate interiors and picturesque gardens.',
  40,
  120,
  ARRAY['historic architecture', 'garden', 'elegant decor', 'parking'],
  false,
  true
),
(
  'Annesdale Mansion',
  'historic',
  '1325 Lamar Ave',
  'Memphis',
  'TN',
  '38104',
  'https://www.zola.com/wedding-vendors/wedding-venues/annesdale-mansion',
  '1850s Italianate villa combining European romantic architecture with vintage Southern charm. Provides an elegant setting for weddings in Midtown Memphis.',
  50,
  180,
  ARRAY['historic architecture', 'elegant decor', 'garden', 'parking'],
  true,
  true
),
(
  'The Atrium at Overton Square',
  'banquet_hall',
  '2085 Madison Ave',
  'Memphis',
  'TN',
  '38104',
  'https://memphiseventgroup.com',
  'Bright, modern event venue in the heart of Overton Square. Features soaring steel arches and high ceilings in an airy contemporary space—perfect for chic urban weddings.',
  75,
  250,
  ARRAY['modern design', 'parking', 'urban location'],
  false,
  true
),
(
  'Memphis Zoo Event Venues',
  'wedding',
  '2000 Prentiss Pl',
  'Memphis',
  'TN',
  '38112',
  'https://www.memphiszoo.org',
  'One-of-a-kind wedding experience among exotic animal exhibits and lush habitats at the Memphis Zoo. Six distinctive ceremony and reception sites offer a truly wild celebration.',
  60,
  300,
  ARRAY['unique venue', 'outdoor space', 'parking', 'catering available'],
  true,
  true
),
(
  'The Great Hall & Conference Center',
  'banquet_hall',
  '1974 Exeter Rd',
  'Germantown',
  'TN',
  '38138',
  'https://www.germantown-tn.gov/thegreathall',
  '8,600 sq ft event center tucked in the heart of Germantown. Surrounded by trees and set below street level, it offers a contemporary space for weddings up to 600 guests.',
  100,
  600,
  ARRAY['large capacity', 'modern design', 'parking'],
  false,
  true
);

-- Verify the insert
SELECT 
  venue_name, 
  city, 
  state, 
  venue_type, 
  capacity_max,
  is_featured
FROM preferred_venues 
ORDER BY is_featured DESC, venue_name;