-- Insert the Silky O'Sullivan's event into live_events table
-- This is the first event created manually, and will serve as a template

INSERT INTO live_events (
  event_id,
  slug,
  title,
  description,
  event_date,
  event_time,
  end_time,
  venue_name,
  venue_address,
  venue_url,
  is_published,
  is_featured,
  cover_photo_url,
  featured_image_url,
  ticketing_enabled,
  ticket_price,
  seo_title,
  seo_description,
  seo_keywords,
  display_order,
  published_at,
  created_at,
  updated_at
) VALUES (
  'dj-ben-murray-silky-osullivans-2026-12-27',
  'dj-ben-murray-silky-osullivans-2026-12-27',
  'DJ Ben Murray Live at Silky O''Sullivan''s',
  'Join DJ Ben Murray for a live performance at Silky O''Sullivan''s on Beale Street! Open to the public. Request your favorite songs and enjoy an unforgettable night of music in the heart of Memphis.',
  '2026-12-27',
  '22:00:00',
  '02:00:00',
  'Silky O''Sullivan''s',
  '183 Beale St, Memphis, TN 38103',
  'https://www.silkyosullivans.com',
  TRUE,
  TRUE,
  'https://www.m10djcompany.com/assets/silky-osullivans-beale-street.jpg',
  'https://www.m10djcompany.com/assets/silky-osullivans-beale-street.jpg',
  TRUE,
  12.00,
  'DJ Ben Murray Live at Silky O''Sullivan''s | December 27, 2026 | Beale Street Memphis',
  'Join DJ Ben Murray for a live performance at Silky O''Sullivan''s on Beale Street, December 27, 2026 at 10pm. Open to the public. Request your favorite songs and enjoy an unforgettable night of music in the heart of Memphis!',
  ARRAY['DJ Ben Murray', 'Silky O Sullivan Beale Street', 'Memphis DJ live performance', 'Beale Street DJ', 'Memphis nightlife', 'DJ event Memphis', 'live music Beale Street', 'Memphis entertainment'],
  0,
  NOW(),
  NOW(),
  NOW()
) ON CONFLICT (event_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  event_date = EXCLUDED.event_date,
  event_time = EXCLUDED.event_time,
  end_time = EXCLUDED.end_time,
  venue_name = EXCLUDED.venue_name,
  venue_address = EXCLUDED.venue_address,
  venue_url = EXCLUDED.venue_url,
  is_published = EXCLUDED.is_published,
  is_featured = EXCLUDED.is_featured,
  cover_photo_url = EXCLUDED.cover_photo_url,
  featured_image_url = EXCLUDED.featured_image_url,
  ticketing_enabled = EXCLUDED.ticketing_enabled,
  ticket_price = EXCLUDED.ticket_price,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  seo_keywords = EXCLUDED.seo_keywords,
  updated_at = NOW();

